# InteractiveSigns v1.4.0
# Author: Vovari2

# True - so that when you insert an item into the signs, it will be three-dimensional (3D)
# False - so that when an item is inserted into the signs, it will be flat (2D)
enable_items_volume: false


# A list of items that will not be allowed to be tabbed (default: empty)
blacklist_of_items:
  - #nothing

# True - so players need the “permission_can_use_signs” permission to insert items into the signs
# False - so all players can insert items into signs
player_need_to_have_permission_to_use_signs: false
# Permission required to insert items into the signs
permission_can_use_signs: "interactive_signs.use"


## Settings for protection plugins
# HuskClaims
huskclaims:
  flag_id: "items_on_signs"

# Lands
lands:
  flag_id: "items_on_signs"
  flag_name: "Items on signs"
  flag_material: "SPRUCE_HANGING_SIGN"
  flag_description: "Flag that allows you to insert and take items from the tablets"