name: InteractiveSigns
author: Vovari2
version: '${version}'
main: me.vovari2.interactivesigns.InteractiveSigns
api-version: '1.20'

softdepend: [CoreProtect, WorldGuard, GriefPrevention, HuskClaims, SuperiorSkyblock2, Lands]
