name: InteractiveSigns
author: Vovari2
version: '${version}'
main: me.vovari2.interactivesigns.InteractiveSigns
api-version: '1.20'
folia-supported: true

softdepend: [PlaceholderAPI, CoreProtect, WorldGuard, Lands, Residence, HuskClaims, GriefPrevention, SuperiorSkyblock2, ChestProtect, GriefDefender]
